%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                 		Datalog
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%          CINEMA DATABASE
%%
%%  artist(aID, anam, nationality)	              	  key: aID
%%  Films(fID, title, director, year, language)	      key: fID
%%  Roles(fID, aID, personage, cost)         	      key: fID, aID
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Artists(123,'KeanuReeves','american').
Artists(415,'MarionCotillard','french').
Artists(420,'ArmandVerdure','french').
Artists(304,'MatthiasSchoenaerts','belgian').
Artists(702,'LauraAntonelli','italian').
Artists(876,'MarcelloMastroianni','italian').
Artists(771,'EmmaStone','american').
Artists(772,'RyanGosling','canadian').
Artists(645,'AudreyHepburn','american').
Artists(639,'HumphreyBogart','american').
Artists(543,'JuliaOrmond','english').
Artists(693,'HarrisonFord','american').

Films(1,'De rouilles et des os',867,2011,'french').
Films(2,'TheMatrix',876,1999,'english').
Films(3,'TheMatrixReloaded',876,2003,'english').
Films(4,'LaLaLand',945,2016,'english').
Films(5,'Sabrina',756,1995,'english').
Films(6,'Sabrina',657,1954,'english').

Roles(1,415,'Stephanie',21000).
Roles(1,420,'Sam',9000).
Roles(2,123,'Neo',10500).
Roles(3,123,'Neo',20000).
Roles(2,702,'FJacques',45000).
Roles(1,304,'Alain',9000).
Roles(4,771,'Mia',100000).
Roles(4,772,'Seb',150000).
Roles(6,645,'Sabrina',34000).
Roles(6,639,'Linus',45000).
Roles(5,543,'Sabrina',67000).
Roles(5,693,'Linus',78000).

% Q1. All the names of the Artists and the titles of the Films in which they have participated.
 
Nametitle(N,T) :- Artists(I,N,_), Roles(F,I,_,_), Films(F,T,_,_,_).

Idfilmfr(A) :- Artists(B1,_,french), Roles(A,B1,_,_), Artists(B2,_,french), Roles(A,B2,_,_)
% idfilmfr(1).