Game("The Legend of Zelda", 1986, 9.0).
Game("Majora's Mask", 2000, 9.7).
Game("Skyward Sword", 2011, 9.0).
Game("Tear of the Kingdom", 2023, 10).
Game("Ocarina of Time", 1998, 9.3).
Game("Breath of the Wild", 2017, 9.7).
Game("A Link to the Past", 1991, 9.1).
Game("Link's Awakening", 1993, 8.8).
Game("Twilight Princess", 2006, 9.2).
Game("Wind Waker", 2002, 9.0).

% IDB
Q1(GameID, Rating) :- Game(GameID, _, Rating), Rating >= 9.8.

PopularGame(GameID) :- Game(GameID, _, Rating), Rating <= 10, Rating > 9.2.

NewerGame(Game1, Game2) :- Game(Game1, Year1, _), Game(Game2, Year2, _), Year1 > Year2.

OlderGame(GameID, Year) :- Game(GameID, Year, _), Year < 2000.

SameRating(Game1, Game2) :- Game(Game1, _, Rating1), Game(Game2, _, Rating2), Rating1 =:= Rating2.

