%% Datalog test suite
%% This file contains a set of test cases with complex combination of predicates for the Datalog interpreter.

% EDB (facts)

% Character(id, name, attack, health)
Character(1, 'Ganondorf', 129, 208)
Character(2, 'Link', 112, 133)
Character(3, 'Zelda', 98, 182)
Character(4, 'Bokoblin', 15, 43)
Character(5, 'Lynel', 88, 322)

% Item(id, name, attack, health)
Item(301, 'Master Sword', 100, 0)
Item(302, 'Hylian Shield', 5, 100)
Item(303, 'Bow of light', 999, 0)
Item(304, 'Axe', 33, 0)
Item(305, 'Stick', 20, 0)
Item(306, 'Lynel Massue', 140, 50)
Item(307, 'Majora's Mask', 0, 999)

% CharacterItem(character_id, item_id)
CharacterItem(2, 301)
CharacterItem(2, 302)
CharacterItem(5, 306)
CharacterItem(4, 305)
CharacterItem(3, 303)

% Fight(id, character_id, enemy_id, winner_id)
Fight(201, 2, 1, 2)
Fight(202, 2, 4, 2)
Fight(203, 2, 5, 5)
Fight(204, 3, 1, 3)
Fight(205, 1, 4, 1)

% IDB

% 1. Character with the highest attack (function max, comparison =:=)
MaxDefence(X, Y, MAX) :- Character(X, Y, _, Z), Max(Z, MAX), Z =:= MAX.

% 2. Character with the minimum attack (function min, comparison =:=)
MinDefence(X, Y, MIN) :- Character(X, Y, _, Z), Min(Z, MIN), Z =:= MIN.

% 3. Character with more than 1 wins (groupped count, comparison >)
MoreThan1Win(X, C) :- Character(Y, X, _, _), Fight(_, Y, _, Y), Count(Y, Y, C), C > 1.
